# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima
# theme: minima
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: kimia.fi

author:
  name: Kimmo Ahokas
  email: kimmo.ahokas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Home of Kimmo Ahokas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kimia.fi" # the base hostname & protocol for your site, e.g. http://example.com
include: [".well-known"]

minima:
  date_format: "%d.%m.%Y"
  # These work starting from minima 3.0 (not yet)
  social_links:
    twitter: kimmoahokas
    github:  kimmoahokas
    facebook: kimmo.ahokas
    linkedin: kimmoahokas
    telegram: KimmoAhokas
    keybase: kimia
    mastodon:
      - username: KimmoAhokas
        instance: mastodon.social
header_pages:
  - about.md
show_excerpts: true
# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:day-:title:output_ext


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
